apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm-excercise
    repoURL: https://github.com/neddy299/argocd-demo
    targetRevision: HEAD
  syncPolicy: {}
  
