namespace:
  name: staging

image:
  name: nginx 
  tag: 1.18.0
  pullPolicy: IfNotPresent

replicaCount: 1

configmap:
  data: "version: 1.18.0"

resources:
  request:
    memory: "128Mi"
    cpu: "50m"
service:
  port: 8111
  type: ClusterIP

