namespace:
  name: demo

image:
  name: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

configmap:
  data: "version: alpine"

resources:
  request:
    memory: "256Mi"
    cpu: "50m"
service:
  port: 8111
  type: ClusterIP

