apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.image.name }}
    tag: {{ .Values.image.tag }}
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8111
  selector:
    app: {{ .Values.image.name }}
    tag: {{ .Values.image.tag }}
  type: {{ .Values.service.type }}

